export { Vault } from "./vault.js";
export { VaultConflictError } from "./types.js";
export type {
  AttachmentMetadata,
  BackupOperation,
  BackupOperationKind,
  GithubBackupState,
  ImportAttachmentInput,
  ImportNoteInput,
  Note,
  NoteMetadata,
  SaveNoteInput,
  VaultId,
  VaultOptions,
  VaultBackupChange,
  VaultBackupManifest,
  VaultBackupSnapshot,
  VaultChangeEvent,
  VaultChangeKind,
  VaultOperationContext,
  VaultOperationOptions,
  VaultRestoreFile,
  VaultRestoreResult,
  VaultSearchResult,
  VaultStorageUsage,
} from "./types.js";
