export { Vault } from "./vault.js";
export { VaultConflictError } from "./types.js";
export {
  createVaultDescriptor,
  defaultVaultDescriptor,
  isDefaultVault,
  normalizeVaultName,
  readVaultRegistry,
  suggestedRepositoryName,
  uniqueVaultName,
  vaultOptions,
  writeVaultRegistry,
  type VaultDescriptor,
  type VaultRegistry,
} from "./registry.js";
export type {
  AttachmentMetadata,
  BackupOperation,
  BackupOperationKind,
  GithubBackupState,
  ImportAttachmentInput,
  ImportNoteInput,
  Note,
  NoteMetadata,
  SaveNoteInput,
  VaultId,
  VaultOptions,
  VaultBackupChange,
  VaultBackupManifest,
  VaultBackupSnapshot,
  VaultChangeEvent,
  VaultChangeKind,
  VaultOperationContext,
  VaultOperationOptions,
  VaultRestoreFile,
  VaultRestoreResult,
  VaultSearchResult,
  VaultStorageUsage,
} from "./types.js";
