export { Vault } from "./vault.js";
export type {
  AttachmentMetadata,
  BackupOperation,
  BackupOperationKind,
  GithubBackupState,
  Note,
  NoteMetadata,
  SaveNoteInput,
  SearchState,
  VaultId,
  VaultOptions,
  VaultBackupChange,
  VaultBackupManifest,
  VaultBackupSnapshot,
  VaultRestoreFile,
  VaultRestoreResult,
  VaultSearchResult,
  VaultStorageUsage,
} from "./types.js";
