import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const catalogPath = path.join(root, "src/lib/theme-catalog.json");
const tokensPath = path.join(root, "src/lib/theme-tokens.json");
const generatedCssPath = path.join(root, "src/routes/styles/color-themes.generated.css");

const catalog = JSON.parse(fs.readFileSync(catalogPath, "utf8"));
const tokens = JSON.parse(fs.readFileSync(tokensPath, "utf8"));
const themeIds = Object.keys(catalog.themes);
const storageKeys = catalog.storageKeys;
const defaultColorTheme = catalog.defaultColorTheme;
const variableNames = Object.keys(tokens.defaults.light);

if (themeIds.length === 0) throw new Error("The theme catalog must contain at least one theme.");
if (!Object.hasOwn(catalog.themes, "ember"))
  throw new Error("The theme catalog must include ember as its base palette.");
if (!Object.hasOwn(catalog.themes, defaultColorTheme))
  throw new Error("The catalog default color theme must be a known theme.");
if (!storageKeys?.mode || !storageKeys?.color)
  throw new Error("The theme catalog must define storage keys.");

for (const id of themeIds) {
  if (!tokens.themes[id]) throw new Error("Missing token overrides for " + id + ".");
  for (const mode of ["light", "dark"]) {
    for (const name of Object.keys(tokens.themes[id][mode])) {
      if (!variableNames.includes(name))
        throw new Error("Unknown token " + name + " in " + id + "/" + mode + ".");
    }
  }
}

function renderBlock(selector, mode, values) {
  const declarations = Object.entries(values)
    .filter(([name]) => variableNames.includes(name))
    .map(([name, value]) => "  " + name + ": " + value + ";")
    .join("\n");
  return selector + " {\n  color-scheme: " + mode + ";\n\n" + declarations + "\n}\n";
}

const cssBlocks = [
  "/* Generated by scripts/generate-themes.mjs. Edit src/lib/theme-tokens.json instead. */\n",
  renderBlock(
    ':root,\n.print-document,\n.output-pane[data-output-theme="light"]',
    "light",
    tokens.defaults.light,
  ),
  renderBlock(
    ':root[data-theme="dark"],\n.output-pane[data-output-theme="dark"]',
    "dark",
    tokens.defaults.dark,
  ),
];

for (const id of themeIds) {
  if (id === "ember") continue;
  cssBlocks.push(
    renderBlock(
      ':root[data-color-theme="' +
        id +
        '"],\n.output-pane[data-color-theme="' +
        id +
        '"][data-output-theme="light"]',
      "light",
      tokens.themes[id].light,
    ),
  );
  cssBlocks.push(
    renderBlock(
      ':root[data-color-theme="' +
        id +
        '"][data-theme="dark"],\n.output-pane[data-color-theme="' +
        id +
        '"][data-output-theme="dark"]',
      "dark",
      tokens.themes[id].dark,
    ),
  );
}

const outputs = new Map([[generatedCssPath, cssBlocks.join("\n")]]);
const check = process.argv.includes("--check");

for (const [filePath, content] of outputs) {
  const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : undefined;
  if (check) {
    if (current !== content) {
      console.error(path.relative(root, filePath) + " is out of date. Run vp run themes:generate.");
      process.exitCode = 1;
    }
  } else if (current !== content) {
    fs.writeFileSync(filePath, content);
  }
}
